export const example1 = {
  id: '0002',
  name: '级联模板',
  jsonData: {
    info: {
      appversion: '',
      company: '',
      createdTime: '',
      creator: '',
      lastmodifiedby: '',
      modifiedTime: '',
      name: '新模板',
    },
    sheets: [
      {
        name: 'Sheet1',
        config: {
          borderInfo: [
            {
              rangeType: 'cell',
              value: {
                row_index: 0,
                col_index: 0,
                l: { color: '#000', style: 1 },
                r: { color: '#000', style: 1 },
                t: { color: '#000', style: 1 },
                b: { color: '#000', style: 1 },
              },
            },
            {
              rangeType: 'range',
              borderType: 'border-all',
              style: '1',
              color: '#000',
              range: [{ row: [0, 0], column: [1, 1] }],
            },
            {
              rangeType: 'range',
              borderType: 'border-all',
              style: '1',
              color: '#000',
              range: [{ row: [1, 1], column: [0, 1] }],
            },
            {
              rangeType: 'cell',
              value: {
                row_index: 1,
                col_index: 0,
                l: { color: '#000', style: 1 },
                r: { color: '#000', style: '1' },
                t: { color: '#000', style: 1 },
                b: { color: '#000', style: '1' },
              },
            },
          ],
          columnlen: { 1: 136, 3: 156 },
          customWidth: { 1: 1, 3: 1 },
          merge: {},
          rowlen: {},
          customHeight: {},
          rowhidden: {},
        },
        index: '1',
        status: 1,
        order: '0',
        zoomRatio: 1,
        showGridLines: '1',
        defaultColWidth: 72,
        defaultRowHeight: 20,
        celldata: [
          {
            r: 0,
            c: 0,
            v: {
              m: '单位类型',
              v: '单位类型',
              bg: '#cfe2f3',
              fs: 10,
              fc: '#000000',
              ff: '微软雅黑',
              ht: 1,
              vt: 1,
              tb: 1,
              ct: { fa: 'General', t: 'g' },
            },
          },
          {
            r: 0,
            c: 1,
            v: { ct: { fa: 'General', t: 'g' }, v: '', m: '' },
          },
          {
            r: 1,
            c: 0,
            v: {
              m: '单位类别',
              v: '单位类别',
              bg: '#cfe2f3',
              fs: 10,
              fc: '#000000',
              ff: '微软雅黑',
              ht: 1,
              vt: 1,
              tb: 1,
              ct: { fa: 'General', t: 'g' },
            },
          },
          { r: 3, c: 3, v: { ct: { fa: 'General', t: 'g' } } },
        ],
        dataVerification: {
          '0_1': {
            type: 'dropdown',
            type2: false,
            value1: '党政机关/事业单位,教育机构,医院,文化体育场',
            value2: '',
            checked: false,
            remote: false,
            prohibitInput: false,
            hintShow: false,
            hintText: '',
          },
        },
      },
    ],
  },
  mapping: [
    {
      cellIndex: { row: 0, column: 1 },
      cellRange: { row: [0, 0], column: [1, 1] },
      cellPosition: { start: 'B1', end: 'B1' },
      fieldName: 'type',
      fieldTitle: '单位类型',
      dataType: 'select',
      events: {
        enable: true,
        augments: ['LuckySheet', 'cellValue', 'mapping'],
        funcBody:
          "/**\n * 示例三：根据当前单元格变更做级联更新，更新 B2 单元格的数据验证为下拉\n * 当前单元格为 党政机关/事业单位,教育机构,医院,文化体育场\n * 更新映射后 为一下对应选项\n * API: setDataVerification(optionItem, [setting])\n */\nconst optionsMap = {\n  '党政机关/事业单位':'独立办公,集中办公',\n  '教育机构':'高等学校,中小学校',\n  '医院':'三级,二级以下',\n  '文化体育场':'/'\n}\n\nconst { newValue }  = cellValue\nconst keyValue = optionsMap[newValue.v]\n\nconsole.log(keyValue)\n\nconst baseOptionItem = {\n  checked: false,\n  hintShow: false,\n  hintText: '',\n  prohibitInput: false,\n  remote: false,\n  type: 'dropdown',\n  type2: false,\n  value1: '',\n  value2: '',\n}\n\nLuckySheet.setDataVerification(\n  {\n    ...baseOptionItem,\n    value1: keyValue,\n  },\n  {\n    range: { row: [1, 1], column: [1, 1] }\n  }\n)\nLuckySheet.setCellValue(1, 1, '')\n",
      },
    },
    {
      cellIndex: { row: 1, column: 1 },
      cellRange: { row: [1, 1], column: [1, 1] },
      cellPosition: { start: 'B2', end: 'B2' },
      fieldName: 'type2',
      fieldTitle: '单位类别',
      dataType: 'select',
      events: {
        enable: false,
        augments: ['LuckySheet', 'cellValue', 'mapping'],
        funcBody: '',
      },
    },
  ],
  isPublish: '0',
  reportCount: 0,
  records: 0,
}
