import { ThemeMainColors } from './default-theme'

export const ThemeSiderPrefabs = [
  {
    name: '极客蓝白',
    config: {
      binColorPrimary: ThemeMainColors[0],
      vSiderBg: 'var(--v-g-bg-color)',
      vSiderBorderColor: 'var(--v-g-border-color)',
      vSiderCollapseBtnColor: 'var(--v-g-text-color-3)',
      vSiderCollapseBtnBg: 'var(--v-g-fill-color-1)',
      vSiderCollapseBtnBgHover: 'var(--v-g-fill-color-3)',
      vMenuItemHeight: '40px',
      vMenuItemBorderRadius: '4px',
      vMenuTextColor: 'var(--v-g-text-color)',
      vMenuTextHoverColor: 'var(--b-menu-text-color)',
      vMenuTextActiveColor: 'var(--bin-color-primary)',
      vMenuBgColor: 'var(--v-sider-bg)',
      vMenuBgHoverColor: 'var(--bin-color-primary-light6)',
      vMenuBgActiveColor: 'var(--bin-color-primary-light6)',
    },
  },
  {
    name: '极致蓝黑',
    config: {
      binColorPrimary: ThemeMainColors[0],
      vSiderBg: '#001428',
      vSiderBorderColor: 'var(--v-g-border-color-dark)',
      vSiderCollapseBtnColor: 'rgba(255, 255, 255, 0.5)',
      vSiderCollapseBtnBg: 'rgba(255, 255, 255, 0.05)',
      vSiderCollapseBtnBgHover: 'rgba(255, 255, 255, 0.12)',
      vMenuTextColor: 'var(--v-g-text-color-4)',
      vMenuTextHoverColor: 'var(--v-g-text-color-4)',
      vMenuBgHoverColor: 'rgba(255, 255, 255, 0.09)',
      vMenuBgActiveColor: 'rgba(255, 255, 255, 0.09)',
    },
  },
  {
    name: '海蔚蓝白',
    config: {
      binColorPrimary: ThemeMainColors[1],
      vSiderBg: 'var(--v-g-bg-color)',
      vSiderBorderColor: 'var(--v-g-border-color)',
      vSiderCollapseBtnColor: 'var(--v-g-text-color-3)',
      vSiderCollapseBtnBg: 'var(--v-g-fill-color-1)',
      vSiderCollapseBtnBgHover: 'var(--v-g-fill-color-3)',
      vMenuItemHeight: '40px',
      vMenuItemBorderRadius: '4px',
      vMenuTextColor: 'var(--v-g-text-color)',
      vMenuTextHoverColor: 'var(--bin-color-primary)',
      vMenuTextActiveColor: 'var(--bin-color-primary)',
      vMenuBgColor: 'var(--v-sider-bg)',
      vMenuBgHoverColor: 'var(--v-g-fill-color-3)',
      vMenuBgActiveColor: 'var(--bin-color-primary-light4)',
    },
  },
  {
    name: '海蔚深蓝',
    config: {
      binColorPrimary: ThemeMainColors[1],
      vSiderBg: '#232324',
      vSiderBorderColor: 'var(--v-g-border-color-dark)',
      vSiderCollapseBtnColor: 'rgba(255, 255, 255, 0.5)',
      vSiderCollapseBtnBg: 'rgba(255, 255, 255, 0.05)',
      vSiderCollapseBtnBgHover: 'rgba(255, 255, 255, 0.12)',
      vMenuItemHeight: '40px',
      vMenuItemBorderRadius: '4px',
      vMenuTextColor: 'var(--v-g-text-color-3)',
      vMenuTextHoverColor: 'var(--bin-color-primary)',
      vMenuTextActiveColor: '#FFFFFF',
      vMenuBgHoverColor: 'rgba(22, 93, 255, 0.09)',
      vMenuBgActiveColor: 'var(--bin-color-primary)',
    },
  },
  {
    name: '绿野仙踪',
    config: {
      binColorPrimary: ThemeMainColors[3],
      vSiderBg: 'var(--v-g-bg-color)',
      vSiderBorderColor: 'var(--v-g-border-color)',
      vSiderCollapseBtnColor: 'var(--v-g-text-color-3)',
      vSiderCollapseBtnBg: 'var(--v-g-fill-color-1)',
      vSiderCollapseBtnBgHover: 'var(--v-g-fill-color-3)',
      vMenuItemHeight: '40px',
      vMenuItemBorderRadius: '4px',
      vMenuTextColor: 'var(--v-g-text-color)',
      vMenuTextHoverColor: 'var(--b-menu-text-color)',
      vMenuTextActiveColor: 'var(--bin-color-primary)',
      vMenuBgColor: 'var(--v-sider-bg)',
      vMenuBgHoverColor: 'var(--bin-color-primary-light6)',
      vMenuBgActiveColor: 'var(--bin-color-primary-light6)',
    },
  },
  {
    name: '森林幻境',
    config: {
      binColorPrimary: ThemeMainColors[3],
      vSiderBg: '#001529',
      vSiderBorderColor: 'var(--v-g-border-color-dark)',
      vSiderCollapseBtnColor: 'rgba(255, 255, 255, 0.5)',
      vSiderCollapseBtnBg: 'rgba(255, 255, 255, 0.05)',
      vSiderCollapseBtnBgHover: 'rgba(255, 255, 255, 0.12)',
      vMenuItemHeight: '40px',
      vMenuItemBorderRadius: '4px',
      vMenuTextColor: 'var(--v-g-text-color-4)',
      vMenuTextHoverColor: 'var(--v-g-text-color-4)',
      vMenuTextActiveColor: 'var(--bin-color-primary)',
      vMenuBgColor: 'var(--v-sider-bg)',
      vMenuBgHoverColor: 'rgba(255, 255, 255, 0.09)',
      vMenuBgActiveColor: 'rgba(255, 255, 255, 0.09)',
    },
  },
  {
    name: '暗夜紫云',
    config: {
      binColorPrimary: ThemeMainColors[4],
      vSiderBg: 'var(--v-g-bg-color)',
      vSiderBorderColor: 'var(--v-g-border-color)',
      vSiderCollapseBtnColor: 'var(--v-g-text-color-3)',
      vSiderCollapseBtnBg: 'var(--v-g-fill-color-1)',
      vSiderCollapseBtnBgHover: 'var(--v-g-fill-color-3)',
      vMenuItemHeight: '42px',
      vMenuItemBorderRadius: '2px',
      vMenuTextColor: 'var(--v-g-text-color)',
      vMenuTextHoverColor: 'var(--b-menu-text-color)',
      vMenuTextActiveColor: 'var(--bin-color-primary)',
      vMenuBgColor: 'var(--v-sider-bg)',
      vMenuBgHoverColor: 'var(--bin-color-primary-light6)',
      vMenuBgActiveColor: 'var(--bin-color-primary-light6)',
    },
  },
  {
    name: '紫黑精灵',
    config: {
      binColorPrimary: ThemeMainColors[4],
      vSiderBg: '#273352',
      vSiderBorderColor: 'var(--v-g-border-color-dark)',
      vSiderCollapseBtnColor: 'rgba(255, 255, 255, 0.5)',
      vSiderCollapseBtnBg: 'rgba(255, 255, 255, 0.05)',
      vSiderCollapseBtnBgHover: 'rgba(255, 255, 255, 0.12)',
      vMenuItemHeight: '40px',
      vMenuItemBorderRadius: '4px',
      vMenuTextColor: 'var(--v-g-text-color-4)',
      vMenuTextActiveColor: 'var(--bin-color-primary-light2)',
      vMenuTextHoverColor: 'var(--v-g-text-color-4)',
      vMenuBgHoverColor: 'rgba(255, 255, 255, 0.09)',
      vMenuBgActiveColor: 'rgba(255, 255, 255, 0.09)',
    },
  },
  {
    name: '活力橙白',
    config: {
      binColorPrimary: ThemeMainColors[7],
      vSiderBg: 'var(--v-g-bg-color)',
      vSiderBorderColor: 'var(--v-g-border-color)',
      vSiderCollapseBtnColor: 'var(--v-g-text-color-3)',
      vSiderCollapseBtnBg: 'var(--v-g-fill-color-1)',
      vSiderCollapseBtnBgHover: 'var(--v-g-fill-color-3)',
      vMenuItemHeight: '40px',
      vMenuItemBorderRadius: '4px',
      vMenuTextColor: 'var(--v-g-text-color)',
      vMenuTextHoverColor: 'var(--b-menu-text-color)',
      vMenuTextActiveColor: 'var(--bin-color-primary)',
      vMenuBgColor: 'var(--v-sider-bg)',
      vMenuBgHoverColor: 'var(--bin-color-primary-light5)',
      vMenuBgActiveColor: 'var(--bin-color-primary-light4)',
    },
  },
  {
    name: '活力橙黑',
    config: {
      binColorPrimary: ThemeMainColors[7],
      vSiderBg: '#191b24',
      vSiderBorderColor: 'var(--v-sider-bg)',
      vSiderCollapseBtnColor: 'rgba(255, 255, 255, 0.5)',
      vSiderCollapseBtnBg: 'rgba(255, 255, 255, 0.05)',
      vSiderCollapseBtnBgHover: 'rgba(255, 255, 255, 0.12)',
      vMenuItemHeight: '40px',
      vMenuItemBorderRadius: '4px',
      vMenuTextColor: 'var(--v-g-text-color-4)',
      vMenuTextActiveColor: 'var(--bin-color-primary-light2)',
      vMenuTextHoverColor: 'var(--v-g-text-color-4)',
      vMenuBgColor: 'var(--v-sider-bg)',
      vMenuBgHoverColor: 'rgba(255, 255, 255, 0.09)',
      vMenuBgActiveColor: 'rgba(255, 255, 255, 0.09)',
    },
  },
  {
    name: '碧海清波',
    config: {
      binColorPrimary: ThemeMainColors[2],
      vSiderBg: 'var(--v-g-bg-color)',
      vSiderBorderColor: 'var(--v-g-border-color)',
      vSiderCollapseBtnColor: 'var(--v-g-text-color-3)',
      vSiderCollapseBtnBg: 'var(--v-g-fill-color-1)',
      vSiderCollapseBtnBgHover: 'var(--v-g-fill-color-3)',
      vMenuItemHeight: '40px',
      vMenuItemBorderRadius: '4px',
      vMenuTextColor: 'var(--v-g-text-color)',
      vMenuTextHoverColor: 'var(--b-menu-text-color)',
      vMenuTextActiveColor: 'var(--bin-color-primary)',
      vMenuBgColor: 'var(--v-sider-bg)',
      vMenuBgHoverColor: 'var(--bin-color-primary-light5)',
      vMenuBgActiveColor: 'var(--bin-color-primary-light5)',
    },
  },
  {
    name: '深青海岸',
    config: {
      binColorPrimary: ThemeMainColors[2],
      vSiderBg: '#304156',
      vSiderBorderColor: 'var(--v-g-border-color-dark)',
      vSiderCollapseBtnColor: 'rgba(255, 255, 255, 0.5)',
      vSiderCollapseBtnBg: 'rgba(255, 255, 255, 0.05)',
      vSiderCollapseBtnBgHover: 'rgba(255, 255, 255, 0.12)',
      vMenuItemHeight: '40px',
      vMenuItemBorderRadius: '4px',
      vMenuTextColor: 'var(--v-g-text-color-4)',
      vMenuTextActiveColor: 'var(--bin-color-primary-light2)',
      vMenuTextHoverColor: 'var(--v-g-text-color-4)',
      vMenuBgColor: 'var(--v-sider-bg)',
      vMenuBgHoverColor: 'rgba(255, 255, 255, 0.09)',
      vMenuBgActiveColor: 'rgba(255, 255, 255, 0.09)',
    },
  },
  {
    name: '红色回忆',
    config: {
      binColorPrimary: ThemeMainColors[6],
      vSiderBg: 'var(--v-g-bg-color)',
      vSiderBorderColor: 'var(--v-g-border-color)',
      vSiderCollapseBtnColor: 'var(--v-g-text-color-3)',
      vSiderCollapseBtnBg: 'var(--v-g-fill-color-1)',
      vSiderCollapseBtnBgHover: 'var(--v-g-fill-color-3)',
      vMenuItemHeight: '40px',
      vMenuItemBorderRadius: '4px',
      vMenuTextColor: 'var(--v-g-text-color)',
      vMenuTextHoverColor: 'var(--b-menu-text-color)',
      vMenuTextActiveColor: 'var(--bin-color-primary)',
      vMenuBgColor: 'var(--v-sider-bg)',
      vMenuBgHoverColor: 'var(--bin-color-primary-light5)',
      vMenuBgActiveColor: 'var(--bin-color-primary-light5)',
    },
  },
  {
    name: '黑红文字',
    config: {
      binColorPrimary: ThemeMainColors[6],
      vSiderBg: '#031d21',
      vSiderBorderColor: 'var(--v-g-border-color-dark)',
      vSiderCollapseBtnColor: 'rgba(255, 255, 255, 0.5)',
      vSiderCollapseBtnBg: 'rgba(255, 255, 255, 0.05)',
      vSiderCollapseBtnBgHover: 'rgba(255, 255, 255, 0.12)',
      vMenuItemHeight: '40px',
      vMenuItemBorderRadius: '4px',
      vMenuTextColor: 'var(--v-g-text-color-4)',
      vMenuTextActiveColor: 'var(--bin-color-primary-light2)',
      vMenuTextHoverColor: 'var(--v-g-text-color-4)',
      vMenuBgColor: 'var(--v-sider-bg)',
      vMenuBgHoverColor: 'rgba(255, 255, 255, 0.09)',
      vMenuBgActiveColor: 'rgba(255, 255, 255, 0.09)',
    },
  },
  {
    name: '青春紫白',
    config: {
      binColorPrimary: ThemeMainColors[5],
      vSiderBg: 'var(--v-g-bg-color)',
      vSiderBorderColor: 'var(--v-g-border-color)',
      vSiderCollapseBtnColor: 'var(--v-g-text-color-3)',
      vSiderCollapseBtnBg: 'var(--v-g-fill-color-1)',
      vSiderCollapseBtnBgHover: 'var(--v-g-fill-color-3)',
      vMenuItemHeight: '40px',
      vMenuItemBorderRadius: '4px',
      vMenuTextColor: 'var(--v-g-text-color)',
      vMenuTextHoverColor: 'var(--b-menu-text-color)',
      vMenuTextActiveColor: 'var(--bin-color-primary)',
      vMenuBgColor: 'var(--v-sider-bg)',
      vMenuBgHoverColor: 'var(--bin-color-primary-light5)',
      vMenuBgActiveColor: 'var(--bin-color-primary-light5)',
    },
  },
  {
    name: '青春紫黑',
    config: {
      binColorPrimary: ThemeMainColors[5],
      vSiderBg: '#28333E',
      vSiderBorderColor: 'var(--v-g-border-color-dark)',
      vSiderCollapseBtnColor: 'rgba(255, 255, 255, 0.5)',
      vSiderCollapseBtnBg: 'rgba(255, 255, 255, 0.05)',
      vSiderCollapseBtnBgHover: 'rgba(255, 255, 255, 0.12)',
      vMenuItemHeight: '40px',
      vMenuItemBorderRadius: '4px',
      vMenuTextColor: 'var(--v-g-text-color-4)',
      vMenuTextActiveColor: 'var(--bin-color-primary-light2)',
      vMenuTextHoverColor: 'var(--v-g-text-color-4)',
      vMenuBgColor: 'var(--v-sider-bg)',
      vMenuBgHoverColor: 'rgba(255, 255, 255, 0.09)',
      vMenuBgActiveColor: 'rgba(255, 255, 255, 0.09)',
    },
  },
  {
    name: '浪漫玫瑰',
    config: {
      binColorPrimary: ThemeMainColors[9],
      vSiderBg: 'var(--v-g-bg-color)',
      vSiderBorderColor: 'var(--v-g-border-color)',
      vSiderCollapseBtnColor: 'var(--v-g-text-color-3)',
      vSiderCollapseBtnBg: 'var(--v-g-fill-color-1)',
      vSiderCollapseBtnBgHover: 'var(--v-g-fill-color-3)',
      vMenuItemHeight: '40px',
      vMenuItemBorderRadius: '4px',
      vMenuTextColor: 'var(--v-g-text-color)',
      vMenuTextHoverColor: 'var(--b-menu-text-color)',
      vMenuTextActiveColor: 'var(--bin-color-primary)',
      vMenuBgColor: 'var(--v-sider-bg)',
      vMenuBgHoverColor: 'var(--bin-color-primary-light5)',
      vMenuBgActiveColor: 'var(--bin-color-primary-light5)',
    },
  },
  {
    name: '深黑玫瑰',
    config: {
      binColorPrimary: ThemeMainColors[9],
      vSiderBg: '#383f45',
      vSiderBorderColor: 'var(--v-g-border-color-dark)',
      vSiderCollapseBtnColor: 'rgba(255, 255, 255, 0.5)',
      vSiderCollapseBtnBg: 'rgba(255, 255, 255, 0.05)',
      vSiderCollapseBtnBgHover: 'rgba(255, 255, 255, 0.12)',
      vMenuItemHeight: '40px',
      vMenuItemBorderRadius: '4px',
      vMenuTextColor: 'var(--v-g-text-color-4)',
      vMenuTextActiveColor: 'var(--bin-color-primary-light1)',
      vMenuTextHoverColor: 'var(--v-g-text-color-4)',
      vMenuBgColor: 'var(--v-sider-bg)',
      vMenuBgHoverColor: 'rgba(255, 255, 255, 0.09)',
      vMenuBgActiveColor: 'rgba(255, 255, 255, 0.09)',
    },
  },
  {
    name: '黄昏恋歌',
    config: {
      binColorPrimary: ThemeMainColors[7],
      vSiderBg: 'var(--v-g-bg-color)',
      vSiderBorderColor: 'var(--v-g-border-color)',
      vSiderCollapseBtnColor: 'var(--v-g-text-color-3)',
      vSiderCollapseBtnBg: 'var(--v-g-fill-color-1)',
      vSiderCollapseBtnBgHover: 'var(--v-g-fill-color-3)',
      vMenuItemHeight: '40px',
      vMenuItemBorderRadius: '4px',
      vMenuTextColor: 'var(--v-g-text-color)',
      vMenuTextHoverColor: 'var(--b-menu-text-color)',
      vMenuTextActiveColor: 'var(--bin-color-primary)',
      vMenuBgColor: 'var(--v-sider-bg)',
      vMenuBgHoverColor: 'var(--bin-color-primary-light5)',
      vMenuBgActiveColor: 'var(--bin-color-primary-light5)',
    },
  },
  {
    name: '静谧夕阳',
    config: {
      binColorPrimary: ThemeMainColors[7],
      vSiderBg: '#292c37',
      vSiderBorderColor: 'var(--v-g-border-color-dark)',
      vSiderCollapseBtnColor: 'rgba(255, 255, 255, 0.5)',
      vSiderCollapseBtnBg: 'rgba(255, 255, 255, 0.05)',
      vSiderCollapseBtnBgHover: 'rgba(255, 255, 255, 0.12)',
      vMenuItemHeight: '40px',
      vMenuItemBorderRadius: '4px',
      vMenuTextColor: 'var(--v-g-text-color-4)',
      vMenuTextActiveColor: 'var(--bin-color-primary-light2)',
      vMenuTextHoverColor: 'var(--v-g-text-color-4)',
      vMenuBgColor: 'var(--v-sider-bg)',
      vMenuBgHoverColor: 'rgba(255, 255, 255, 0.09)',
      vMenuBgActiveColor: 'rgba(255, 255, 255, 0.09)',
    },
  },
]
