export const ThemeTagsPrefabs = [
  {
    name: '默认主题',
    config: {
      vTagsBgColor: 'var(--v-g-bg-color)',
      vTagsBorderColor: 'var(--v-g-border-color)',
      vTagsHeight: '32px',
      vTagsFontSize: '12px',
      vTagsItemBorderRadius: '2px',
      vTagsTextColor: 'var(--v-g-text-color)',
      vTagsTextHoverColor: 'var(--v-g-text-color)',
      vTagsTextActiveColor: 'var(--bin-color-primary)',
      vTagsItemBgColor: 'var(--v-g-fill-color-2)',
      vTagsItemBgHoverColor: 'var(--v-g-fill-color-2)',
      vTagsItemBgActiveColor: 'var(--v-g-fill-color-2)',
      vTagsItemBorderColor: 'var(--v-g-fill-color-2)',
      vTagsItemBorderHoverColor: 'var(--v-g-fill-color-2)',
      vTagsItemBorderActiveColor: 'var(--v-g-fill-color-2)',
    },
  },
  {
    name: '主色高亮',
    config: {
      vTagsBgColor: 'var(--v-g-bg-color)',
      vTagsBorderColor: 'var(--v-g-border-color)',
      vTagsHeight: '32px',
      vTagsFontSize: '12px',
      vTagsItemBorderRadius: '2px',
      vTagsTextColor: 'var(--v-g-text-color)',
      vTagsTextHoverColor: 'var(--bin-color-primary)',
      vTagsTextActiveColor: '#fff',
      vTagsItemBgColor: 'var(--v-g-fill-color-2)',
      vTagsItemBgHoverColor: 'var(--bin-color-primary-light5)',
      vTagsItemBgActiveColor: 'var(--bin-color-primary)',
      vTagsItemBorderColor: 'var(--v-g-fill-color-2)',
      vTagsItemBorderHoverColor: 'var(--bin-color-primary-light5)',
      vTagsItemBorderActiveColor: 'var(--bin-color-primary)',
    },
  },
  {
    name: '卡片风格',
    config: {
      vTagsBgColor: 'var(--v-g-bg-color)',
      vTagsBorderColor: 'var(--v-g-border-color)',
      vTagsHeight: '38px',
      vTagsFontSize: '12px',
      vTagsItemBorderRadius: '2px',
      vTagsTextColor: 'var(--v-g-text-color)',
      vTagsTextHoverColor: 'var(--bin-color-primary)',
      vTagsTextActiveColor: 'var(--bin-color-primary)',
      vTagsItemBgColor: '#fff',
      vTagsItemBgHoverColor: '#fff',
      vTagsItemBgActiveColor: 'var(--bin-color-primary-light5)',
      vTagsItemBorderColor: 'var(--v-g-fill-color-2)',
      vTagsItemBorderHoverColor: 'var(--bin-color-primary)',
      vTagsItemBorderActiveColor: 'var(--bin-color-primary)',
    },
  },
  {
    name: '圆角风格',
    config: {
      vTagsBgColor: 'var(--v-g-bg-color)',
      vTagsBorderColor: 'var(--v-g-border-color)',
      vTagsHeight: '32px',
      vTagsFontSize: '12px',
      vTagsItemBorderRadius: '16px',
      vTagsTextColor: 'var(--v-g-text-color)',
      vTagsTextHoverColor: 'var(--v-g-text-color)',
      vTagsTextActiveColor: 'var(--bin-color-primary)',
      vTagsItemBgColor: '#fff',
      vTagsItemBgHoverColor: 'var(--v-g-fill-color-2)',
      vTagsItemBgActiveColor: 'var(--bin-color-primary-light5)',
      vTagsItemBorderColor: 'var(--v-g-fill-color-2)',
      vTagsItemBorderHoverColor: 'var(--bin-color-primary-light5)',
      vTagsItemBorderActiveColor: 'var(--bin-color-primary-light5)',
    },
  },
  {
    name: '深色背景',
    config: {
      vTagsBgColor: 'var(--v-g-bg-color-2)',
      vTagsBorderColor: 'var(--v-g-border-color)',
      vTagsHeight: '32px',
      vTagsFontSize: '12px',
      vTagsItemBorderRadius: '2px',
      vTagsTextColor: 'rgba(255, 255, 255, 0.9)',
      vTagsTextHoverColor: 'rgba(255, 255, 255, 0.9)',
      vTagsTextActiveColor: 'var(--bin-color-primary-light1)',
      vTagsItemBgColor: 'rgba(255, 255, 255, 0.08)',
      vTagsItemBgHoverColor: 'rgba(255, 255, 255, 0.08)',
      vTagsItemBgActiveColor: 'rgba(255, 255, 255, 0.08)',
      vTagsItemBorderColor: 'transparent',
      vTagsItemBorderHoverColor: 'transparent',
      vTagsItemBorderActiveColor: 'transparent',
    },
  },
  {
    name: '跟随侧栏',
    config: {
      vTagsBgColor: 'var(--v-sider-bg)',
      vTagsBorderColor: 'var(--v-sider-border-color)',
      vTagsHeight: '32px',
      vTagsFontSize: '12px',
      vTagsItemBorderRadius: '2px',
      vTagsTextColor: 'var(--v-menu-text-color)',
      vTagsTextHoverColor: 'var(--v-menu-text-hover-color)',
      vTagsTextActiveColor: 'var(--v-menu-text-active-color)',
      vTagsItemBgColor: 'var(--v-menu-bg-color)',
      vTagsItemBgHoverColor: 'var(--v-menu-bg-hover-color)',
      vTagsItemBgActiveColor: 'var(--v-menu-bg-active-color)',
      vTagsItemBorderColor: 'transparent',
      vTagsItemBorderHoverColor: 'transparent',
      vTagsItemBorderActiveColor: 'transparent',
    },
  },
]
